apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: aws-cli-automation

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  execute:
    steps:
      - name: Log in to AWS
        uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::189768267137:role/cloudbees-infra-mgmt
          role-duration-seconds: "3600"
      - name: Run AWS CLI Command
        uses: docker://amazon/aws-cli
        run: |
          aws ec2 describe-instances

  setup-ado:
    steps:
      - name: Setup Azure DevOps CLI
        uses: docker://mcr.microsoft.com/azure-cli:latest
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          ADO_ORG: ${{ vars.AZURE_DEVOPS_ORG }}
        run: |
          # Install Azure DevOps extension
          az extension add --name azure-devops

          # Login using PAT
          echo $AZURE_DEVOPS_EXT_PAT | az devops login --organization $ADO_ORG

          # Verify connection
          az devops project list --output table

  update-work-item:
    steps:
      - name: Update Work Item Status
        uses: docker://mcr.microsoft.com/azure-cli:latest
        env:
          AZURE_DEVOPS_EXT_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
          ADO_ORG: ${{ vars.AZURE_DEVOPS_ORG }}
          PROJECT_NAME: "My Test Project"
          WORK_ITEM_ID: "12345"  # Could be extracted from commit message
        run: |
          az extension add --name azure-devops
          echo $AZURE_DEVOPS_EXT_PAT | az devops login --organization $ADO_ORG

          # Update work item state
          az boards work-item update \
            --id $WORK_ITEM_ID \
            --state "Done" \
            --project $PROJECT_NAME

          # Add deployment comment
          az boards work-item update \
            --id $WORK_ITEM_ID \
            --discussion "Deployed via CloudBees build $CLOUDBEES_RUN_NUMBER at $CLOUDBEES_RUN_URL" \
            --project $PROJECT_NAME

          echo "Work item $WORK_ITEM_ID updated successfully"