apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: aws-cli-automation

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout


jobs:
  execute:
    steps:
      - name: Log in to AWS
        uses: https://github.com/cloudbees-io/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::189768267137:role/cloudbees-infra-mgmt
          role-duration-seconds: "3600"
      - name: Run AWS CLI Command
        uses: docker://amazon/aws-cli
        run: |
          aws ec2 describe-instances
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
